# -*- coding: utf-8 -*-
"""full_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/msc-acse/acse-9-independent-research-project-Garethlomax/blob/full_data_run/full_data.ipynb

#imports
"""
"""

TODO: SORT OUT SHAPE BEING DEFINED IN CLASS.

"""


# all torch imports
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader, Dataset
import torchvision.transforms as transforms
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
import random

import matplotlib.pyplot as plt
import h5py

from sklearn.metrics import f1_score, multilabel_confusion_matrix
import matplotlib.pyplot as plt
import h5py


#
#torch.backends.cudnn.benchmark = True
#torch.backends.cudnn.enabled = True

from sklearn.metrics import roc_curve, roc_auc_score, average_precision_score
import pandas as pd


#torch.backends.cudnn.benchmark = True
#torch.backends.cudnn.enabled = True

#h5py.run_tests()

"""## snippet to investigate ram"""



#device = 'cpu'
#if torch.cuda.device_count() > 0 and torch.cuda.is_available():
#    print("Cuda installed! Running on GPU!")
#    print("GPUs:", torch.cuda.device_count())
#    device = 'cuda'
#else:
#    print("No GPU available!")


def set_seed(seed):
    """
    Use this to set ALL the random seeds to a fixed value and take out any randomness from cuda kernels
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = True  ##uses the inbuilt cudnn auto-tuner to find the fastest convolution algorithms. -
    torch.backends.cudnn.enabled   = True

    return True

#set_seed(42)

"""# LSTM CELL"""

"""TODO: CUDIFY EVERYTHING"""





class LSTMunit(nn.Module):
    """Base unit for an overall convLSTM structure.

    Implementation of ConvLSTM in Pythorch. Used as a worker class for
    LSTMmain. Performs Full ConvLSTM Convolution as introduced in XXXX.
    Automatically uses a padding to ensure output image is of same height
    and width as input.
    Each cell takes an input the data at the current timestep Xt, and a hidden
    representation from the previous timestep Ht-1
    Each cell outputs Ht

    Attributes
    ----------
    input_channels: int
        The number of channels in the input image tensor.
    output_channels: int
        The number of channels in the output image tensor following
        convoluton.
    kernel_size: int
        The size of the kernel used in the convolutional opertation.
    padding: int
        The padding in each of the convolutional operations. Automatically
        calculated so each convolution maintains input image dimensions.
    stride: int
        The stride of input convolutions.
    filter_name_list: str
        List of identifying filter names as used in equations from XXXX.
    conv_dict: dict
        nn.Module Dictionary of pytorch convolution modules, with parameters
        specified by attributes listed above. Stored in Module Dict to make
        accessible to pytorch autograd. See pytorch for explanation of
        computational tree tracking in pytorch.
    shape: int, list
        List of dimensions of image input.
    Wco: double, tensor
        Pytorch parameter tracked tensor for use in hammard operation in
        LSTM logic gates. Is a pytorch parameter to allow computational
        tree tracking.
    Wcf: double, tensor
        Pytorch parameter tracked tensor for use in hammard operation in
        LSTM logic gates. Is a pytorch parameter to allow computational
        tree tracking.
    Wci: double, tensor
        Pytorch parameter tracked tensor for use in hammard operation in
        LSTM logic gates. Is a pytorch parameter to allow computational
        tree tracking.
    tanh: class
        Pytorch tanh class.
    sig: class
        Pytorch sigmoid class.


    """
    def __init__(self, input_channel_no, hidden_channels_no, kernel_size, stride = 1):
        """Constructor method for LSTM

        Parameters
        ----------
        input_channel_no: int
            Number of channels of the input image in the LSTM unit
        hidden_channel_no: int
            The number of hidden channels of the image output by the unit
        kernel_size: int
            The dimension of the square convolutional kernel used in the forward
            method
        stride: int
            depractated"""
        super(LSTMunit, self).__init__()




        self.input_channels = input_channel_no

        self.output_channels = hidden_channels_no

        self.kernel_size = kernel_size

        self.padding = (int((self.kernel_size - 1) / 2 ), int((self.kernel_size - 1) / 2 ))#to ensure output image same dims as input
        # as in conv nowcasting - see references
        self.stride = stride # for same reasons as above stride must be 1.
        """TODO: CHANGE THIS LAYOUT OF CONVOLUTIONAL LAYERS. """
        """ TODO : DEAL WITH BIAS HERE. """
        """ TODO: CAN INCLUDE BIAS IN ONE OF THE CONVOLUTIONS BUT NOT ALL OF THEM - OR COULD INCLUDE IN ALL? """
        """ TODO: decide whether this should be put into function. """
        """TODO: put correct dimensions of tensor in shape"""
        """TODO: DEFINE THESE SYMBOLS. """
        """TODO: PUT THIS IN CONSTRUCTOR."""
        self.filter_name_list = ['Wxi', 'Wxf', 'Wxc', 'Wxo','Whi', 'Whf', 'Whc', 'Who']
        # list of concolution instances for each lstm cell step
        # Filters with Wx_ are unbiased, filters with Wh_ are biased.
        # Stored in module dict to track as parameter.
        self.conv_list = [nn.Conv2d(self.input_channels, self.output_channels, kernel_size =  self.kernel_size, stride = self.stride, padding = self.padding, bias = False).cuda() for i in range(4)]
        self.conv_list = self.conv_list + [(nn.Conv2d(self.output_channels, self.output_channels, kernel_size =  self.kernel_size, stride = self.stride, padding = self.padding, bias = True).cuda()).double() for i in range(4)]
        self.conv_dict = nn.ModuleDict(zip(self.filter_name_list, self.conv_list))

#         self.conv_list = [nn.Conv2d(self.input_channels, self.output_channels, kernel_size =  self.kernel_size, stride = self.stride, padding = self.padding, bias = False) for i in range(4)]
#         self.conv_list = self.conv_list + [(nn.Conv2d(self.output_channels, self.output_channels, kernel_size =  self.kernel_size, stride = self.stride, padding = self.padding, bias = True)).double() for i in range(4)]
#         self.conv_list = nn.ModuleList(self.conv_list)

        # of dimensions seq length, hidden layers, height, width
        shape = [1, self.output_channels, 16, 16]

        # Wco, Wcf, Wci defined as tensors as are multiplicative, not convolutions
        # Tracked as a parameter to allow differentiability.
        self.Wco = nn.Parameter((torch.zeros(shape).double()).cuda(), requires_grad = True)
        self.Wcf = nn.Parameter((torch.zeros(shape).double()).cuda(), requires_grad = True)
        self.Wci = nn.Parameter((torch.zeros(shape).double()).cuda(), requires_grad = True)


#         self.Wco = nn.Parameter((torch.zeros(shape).double()), requires_grad = True)
#         self.Wcf = nn.Parameter((torch.zeros(shape).double()), requires_grad = True)
#         self.Wci = nn.Parameter((torch.zeros(shape).double()), requires_grad = True)
#         self.Wco.name = "test"
#         self.Wco = torch.zeros(shape, requires_grad = True).double()
#         self.Wcf = torch.zeros(shape, requires_grad = True).double()
#         self.Wci = torch.zeros(shape, requires_grad = True).double()

        # activation functions.
        self.tanh = torch.tanh
        self.sig  = torch.sigmoid

#     (1, 6, kernel_size=5, padding=2, stride=1).double()
    def forward(self, x, h, c):
        """Pytorch module forward method.

        Calculates a forward pass of the LSTMunit. Takes in the sequence input
        at a timestep, and previous hidden states and cell memories and returns
        the new hidden state and cell memory, as according to the outline in
        XXXX.

        Parameters
        ----------

        x: tensor, double
            Pytorch tensor of dimensions shape, as specified in class constructor
            tensor should be 3 dimensional tensor of dimensions (input channels,
            height, width). x is the image at a single step of an image sequence
        h: tensor, double
            Pytorch tensor of dimensions (output channels, height, width). h is
            the output hidden state from the last step in the LSTM sequence
        c: tensor, double
            Pytorch tensor of dimensions (output channels, height, width). h is
            the output cell memory state from the last step in the LSTM sequence

        Returns
        -------

        h_t: tensor, double
            Tensor of the new hidden state for the current timestep, Pytorch
            tensor of dimensions (output channels, height, width)
        c_t: tensor, double
            Tensor of the new cell memory state for the current tinestep, Pytorch
            tensor of dimensions (output channels, height, width)
        """

        # Calculates as in Nowcasting Paper. see url for explanation
        i_t = self.sig(self.conv_dict['Wxi'](x) + self.conv_dict['Whi'](h) + self.Wci * c)
        f_t = self.sig(self.conv_dict['Wxf'](x) + self.conv_dict['Whf'](h) + self.Wcf * c)
        c_t = f_t * c + i_t * self.tanh(self.conv_dict['Wxc'](x) + self.conv_dict['Whc'](h))
        o_t = self.sig(self.conv_dict['Wxo'](x) + self.conv_dict['Who'](h) + self.Wco * c_t)
        h_t = o_t * self.tanh(c_t)


        return h_t, c_t

"""# lstm full unit"""

"""TODO: IMPORTANT
WHEN COPYING STATES OVER, INITIAL STATE OF DECODER IS BOTH LAST H AND LAST C
FROM THE LSTM BEING COPIED FROM.

WE ALSO NEED TO INCLUDE THE ABILITY TO OUTPUT THE LAST H AND C AT EACH TIMESTEP
AS INPUT.
"""


""" SEQUENCE, BATCH SIZE, LAYERS, HEIGHT, WIDTH"""

class LSTMmain(nn.Module):
    """Full ConvLSTM module

    Full implementation of a ConvLSTM, for use alone or as part of an encoder
    decoder model. The class initialises and iterates over collections of ConvLSTM
    units.

    Attributes
    ----------

    input_channel_no: int
        The number of input channels in the input image sequence
    hidden_channel_no: int
        The number of channels in the output image sequence
    kernel_size: int
        The size of the kernel used in the convolutional opertation.
    test_input: int, list
        Describes the number of hidden channeels in the layers of the multilayer
        ConvLSTM. Is a list of minimum length 1. i.e a ConvLSTM with 3 layers
        with 2 hidden states in each would have test_input = [2,2,2]
    copy_bool : boolean, list
        List of booleans for each layer of the ConvLSTM specifying if a hidden
        state is to be copied in as the initial hidden state of the layer. This
        is for use in encoder - decoder architectures
    debug: boolean
        Controls print statements for debugging



    """


    """ collection of units to form encoder/ decoder branches - decide which are which
    need funcitonality to copy in and copy out outputs.


    layer output is array of booleans selectively outputing for each layer i.e
    for three layer can have output on second and third but not first with
    layer_output = [0,1,1]"""

    """TODO: DECIDE ON OUTPUT OF HIDDEN CHANNEL LIST """
    def __init__(self, shape, input_channel_no, hidden_channel_no, kernel_size, layer_output, test_input, copy_bool = False, debug = False, save_outputs = True, decoder = False, second_debug = False):
        super(LSTMmain, self).__init__()

        """TODO: USE THIS AS BASIS FOR ENCODER DECODER."""
        """TODO: SPECIFY SHAPE OF INPUT VECTOR"""

        """TODO: FIGURE OUT HOW TO IMPLEMENT ENCODER DECODER ARCHITECUTRE"""
        self.copy_bool = copy_bool

        self.test_input = test_input

        self.debug = debug
        self.second_debug = second_debug
        self.save_all_outputs = save_outputs

        self.shape = shape

        """specify dimensions of shape - as in channel length ect. figure out once put it in a dataloader"""

        self.layers = len(test_input) #number of layers in the encoder.

        self.seq_length = shape[1]

        self.enc_len = len(shape)

        self.input_chans = input_channel_no

        self.hidden_chans = hidden_channel_no

        self.kernel_size = kernel_size

        self.layer_output = layer_output

        # initialise the different conv cells.
#         self.unit_list = [LSTMunit(input_channel_no, hidden_channel_no, kernel_size) for i in range(self.enc_len)]
        self.dummy_list = [input_channel_no] + list(self.test_input) # allows test input to be an array
        if self.debug:
            print("dummy_list:")
            print(self.dummy_list)

#         self.unit_list = nn.ModuleList([(LSTMunit(self.dummy_list[i], self.dummy_list[i+1], kernel_size).double()).cuda() for i in range(len(self.test_input))])
        self.unit_list = nn.ModuleList([(LSTMunit(self.dummy_list[i], self.dummy_list[i+1], kernel_size).double()).cuda() for i in range(len(self.test_input))])

        if self.debug:
            print("number of units:")
            print(len(self.unit_list))
#             print("number of ")

#         self.unit_list = nn.ModuleList(self.unit_list)


    def forward(self, x, copy_in = False, copy_out = [False, False, False]):
        """Forward method of the ConvLSTM

        Takes a sequence of image tensors and returns the hidden state output
        of the final LSTM layer. Takes in hidden state tensors for intermediate
        layers to allow for use in decoder models. The method can copy out specified
        hidden states to allow for use in encoder models.

        Parameters
        ----------
        x : double, tensor
            Input image sequence tensor, of dimensions (minibatch size, sequence
            length, channels, height, width)
        copy_in: list of double tensors
            List of hidden state tensors to be copied in to LSTM layers specified
            by copy_bool. copy_in should only contain the hidden state tensors
            for the require a copied in state. The states should be arranged in
            order, so that the hidden state to be copied into the first layer
            is first.
        copy_out: boolean, list
            List of booleans specifying which layer hidden states are to be copied
            out due to being required to be passed to a decoder.

        Returns
        -------
        x: double, tensor
            Tensor of the hidden state outputs of the final LSTM layer. x is of
            shape (minibatch size, image sequence length, final hidden channel
            number, height, width)
        internal_outputs: tensor, list
            Last hidden states of layers specified by copy_out. To be used in
            encoder LSTM to be copied into decoder LSTM as the copy_in parameter

        """
#     def forward(self, x):
#         copy_in = False
#         copy_out = [False, False, False]


#         print("IS X CUDA?")
#         print(x.is_cuda)
        """loop over layers, then over hidden states

        copy_in is either False or is [[h,c],[h,c]] ect.

        THIS IN NOW CHANGED TO COPY IN

        """

        internal_outputs = []
        """TODO: HOW MANY OUTPUTS TO SAVE"""
        """ S """

        """ TODO: PUT INITIAL ZERO THROUGH THE SYSTEM TO DEFINE H AND C"""

        layer_output = [] # empty list to save each h and c for each step.
        """TODO: DECIDE WHETHER THE ABOVE SHOULD BE ARRAY OR NOT"""

        # x is 5th dimensional tensor.
        # x is of size batch, sequence, layers, height, width

        """TODO: INITIALISE THESE WITH VECTORS."""
        # these need to be of dimensions (batchsizze, hidden_dim, heigh, width)

        size = x.shape

        # need to re arrange the outputs.


        """TODO: SORT OUT H SIZING. """

        batch_size = size[0]
        # change this. h should be of dimensions hidden size, hidden size.
        h_shape = list(x.shape[:1] + x.shape[2:]) # seq is second, we miss it with fancy indexing
        h_shape[1] = self.hidden_chans
        if self.debug:
            print("h_shape:")
            print(h_shape)

        # size should be (seq, batch_size, layers, height, weight)


        empty_start_vectors = []


        #### new method of copying vectors. copy_bool, assigned during object
        # construction now deals iwth copying in values.
        # copy in is still used to supply the tensor values.

        k = 0 # to count through our input state list.
        for i in range(self.layers):
            if self.copy_bool[i]: # if copy bool is true for this layer
                # check purpose of h_shape in below code.
                empty_start_vectors.append(copy_in[k])
                # copies in state for that layer
                """TODO: CHECK IF THIS NEEDS TO BE DETATCHED OR NOT"""
                k += 1 # iterate through input list.

            else: # i.e if false
                assert self.copy_bool[i] == False, "copy_bool arent bools"

                h_shape = list(x.shape[:1] + x.shape[2:]) # seq is second, we miss it with fancy indexing
                h_shape[1] = self.dummy_list[i+1] # check indexing.
                empty_start_vectors.append([(torch.zeros(h_shape).double()).cuda(), (torch.zeros(h_shape).double()).cuda()])

        del k # clear up k so no spare variables flying about.




#         for i in range(self.layers):
#             """CHANGED: NOW HAS COPY IN COPY OUT BASED ON [[0,0][H,C]] FORMAT"""
#             if copy_in == False: # i.e if no copying in occurs then proceed as normal
#                 h_shape = list(x.shape[:1] + x.shape[2:]) # seq is second, we miss it with fancy indexing
#                 h_shape[1] = self.dummy_list[i+1] # check indexing.
# #                 empty_start_vectors.append([(torch.zeros(h_shape).double()).cuda(), (torch.zeros(h_shape).double()).cuda()])
#                 empty_start_vectors.append([(torch.zeros(h_shape).double()).cuda(), (torch.zeros(h_shape).double()).cuda()])
# #             elif copy_in[i] == [0,0]:
#             elif isinstance(copy_in[i], list):

#                 assert (len(copy_in) == self.layers), "Length disparity between layers, copy in format"

#                 # if no copying in in alternate format
#                 h_shape = list(x.shape[:1] + x.shape[2:]) # seq is second, we miss it with fancy indexing
#                 h_shape[1] = self.dummy_list[i+1] # check indexing.
#                 empty_start_vectors.append([(torch.zeros(h_shape).double()).cuda(), (torch.zeros(h_shape).double()).cuda()])

#             else: # copy in the provided vectors
#                 assert (len(copy_in) == self.layers), "Length disparity between layers, copy in format"

#                 """TODO: DECIDE WHETHER TO CHANGE THIS TO AN ASSERT BASED OFF TYPE OF TENSOR."""
#                 empty_start_vectors.append(copy_in[i])





#         empty_start_vectors = [[torch.zeros(h_shape), torch.zeros(h_shape)] for i in range(self.layers)]



        if self.debug:
            for i in empty_start_vectors:
                print(i[0].shape)
            print(" \n \n \n")

#         for i in range(self.layers):
#             empty_start_vectors.append([torch.tensor()])

        total_outputs = []


        for i in range(self.layers):


            layer_output = []
            if self.debug:
                print("layer iteration:")
                print(i)
            # for each in layer

            """AS WE PUT IN ZEROS EACH TIME THIS MAKES OUR LSTM STATELESS"""
            # initialise with zero or noisy vectors
            # at start of each layer put noisy vector in
            # look at tricks paper to find more effective ideas of how to put this in
            # do we have to initialise with 0 tensors after we go to the second layer
            # or does the h carry over???
            """TODO: REVIEW THIS CHANGE"""

            # copy in for each layer.
            # this is used for encoder decoder architectures.
            # default is to put in empty vectors.

            """TODO: REVIEW THIS SECTION"""
            """CHANGED: TO ALWAYS CHOOSE H AND C"""
#             if copy_in == False:
#                 h, c = empty_start_vectors[i]
#             else: h, c = copy_in[i]

            h, c = empty_start_vectors[i]

            if self.debug:
                print("new h shape")
                print(h.shape)

            """TODO: DO WE HAVE TO PUT BLANK VECTORS IN AT EACH TIMESTEP?"""

            # need to initialise zero states for c and h.
            for j in range(self.seq_length):
                if self.debug:
                    print("inner loop iteration:")
                    print(j)
                if self.debug:
                    print("x dtype is:" , x.dtype)
                # for each step in the sequence
                # put x through
                # i.e put through each x value at a given time.

                """TODO: PUT H IN FROM PREVIOUS LAYER, BUT C SHOULD BE ZEROS AT START"""

                if self.debug:
                    print("inner loop size:")
                    print(x[:,j].shape)
                    print("h size:")
                    print(h.shape)

                h, c = self.unit_list[i](x[:,j], h, c)

                # this is record for each output in given layer.
                # this depends whether copying out it enabld
#                 i
                layer_output.append([h, c])

            """TODO: IMPLEMENT THIS"""
#             if self.save_all_outputs[i]:
#                 total_outputs.append(layer_outputs[:,0]) # saves h from each of the layer outputs

            # output
            """OUTSIDE OF SEQ LOOP"""
            """TODO: CHANGE TO NEW OUTPUT METHOD."""
            if copy_out[i] == True:
                # if we want to copy out the contents of this layer:
                internal_outputs.append(layer_output[-1])
                # saves last state and memory which can be subsequently unrolled.
                # when used in an encoder decoder format.
            """removed else statement"""
#             else:
#                 internal_outputs.append([0,0])
                # saves null variable so we can check whats being sent out.


            h_output = [i[0] for i in layer_output] #layer_output[:,0] # take h from each timestep.
            if self.debug:
                print("h_output is of size:")
                print(h_output[0].shape)


            """TODO: REVIEW IF 1 IS THE CORRECT AXIS TO CONCATENATE THE VECTORS ALONG"""
            # we now use h as the predictor input to the other layers.
            """TODO: STACK TENSORS ALONG NEW AXIS. """


            x = torch.stack(h_output,0)
            x = torch.transpose(x, 0, 1)
            if self.second_debug:
                print("x shape in LSTM main:" , x.shape)
            if self.debug:
                print("x reshaped dimensions:")
                print(x.shape)

#         x = torch.zeros(x.shape)
#         x.requires_grad = True
        return x , internal_outputs # return new h in tensor form. do we need to cudify this stuff

    def initialise(self):
        """put through zeros to start everything"""

"""# lstm enc dec onestep"""

# test2 = LSTMmain(shape, 1, 3, 5, [1], test_input = [1,2], debug = False).double()



class LSTMencdec_onestep(nn.Module):
    """Class to allow easy construction of ConvLSTM Encoder-Decoder models

    Constructs ConvLSTM encoder - decoder models using LSTMmain. Takes structure
    argument to specify architecture of initialised model. The structure is a
    2D numpy array. The top row of the array defines the encoder, the bottom
    row defines the encoder. Non zero values in the encoder and decoder rows
    define the number of layers and the hidden channel number for each layer
    of the encoder decoder model. 0 values after a positive in an encoder row
    denote the end of the encoder. 0 values precede the hidden channel
    specification for the decoder. A column overlap between two non zero values
    means that the hidden states are copied out of the corresponding encoder layer
    and into the decoder model. An encoder that has hidden channels of size
    6, and 12, and decoder that reduces the prediction to 6 channels symmetrically
    would be input as: structure = [[6,12,0,],
                                    [0,12,6]]

    Attributes
    ----------

    Structure: int, list


    """

    def __init__(self, structure, input_channels, kernel_size = 5, debug = True):
        """Constructor for LSTMencdec

        Constructs two intances of LSTMmain, one encoder and one decoder. passes
        structure argument to input_test function to produce the analytics of
        the functions.

        Parameters
        ----------
        structure: array of ints
            2d array of ints used to specify structure of encoder decoder. The
            top row of the array defines the encoder, the second row of the array
            defines the decoder. Non zero digits signify then number of channels
            in the hidden state for each layer. Zero digits specify the end of
            the encoder, and are used before the initial digits of the decoder
            as a placeholder. Vertical overlap of non zero digits specifies
            that the hidden state of the encoder layer will be copied as the initial
            state into the corresponding decoder layer. An example outputting
            an image sequence of 5 hidden layers is shown.
            structure = [[6,12,24,0,0,0],
                         [0,0,24,12,8,5]].
        input_channels: int
            The number of channels of each image in the image input sequence to
            the encoder decoder.
        kernel_size: int, optional
            The size of the convolution kernel to be used in the encoder and
            decoder layers.
        debug: bool, optional
            Switch to turn off debugging print statements.
        """


        super(LSTMencdec_onestep, self).__init__()
#         assert isinstance(structure, np.array), "structure should be a 2d numpy array"
        assert len(structure.shape) == 2, "structure should be a 2d numpy array with two rows"
        self.debug = debug

        """TODO: MAKE KERNEL SIZE A LIST SO CAN SPECIFY AT EACH JUNCTURE."""
        shape = [1,10,3,16,16]

        self.structure = structure
        """STRUCTURE IS AN ARRAY - CANNOT USE [] + [] LIST CONCATENATION - WAS ADDING ONE ONTO THE ARRAY THING."""
        self.input_channels = input_channels
        self.kernel_size = kernel_size

        """TODO: ASSERT THAT DATATYPE IS INT."""

        self.enc_shape, self.dec_shape, self.enc_copy_out, self.dec_copy_in = self.input_test()

        if self.debug:
            print("enc_shape, dec_shape, enc_copy_out, dec_copy_in:")
            print(self.enc_shape)
            print(self.dec_shape)
            print(self.enc_copy_out)
            print(self.dec_copy_in)



#         self.sig = nn.Sigmoid()

         # why does this have +1 at third input and decoder hasnt??????

        self.encoder = LSTMmain(shape, self.input_channels, len(self.enc_shape)+1, self.kernel_size, layer_output = self.enc_copy_out, test_input = self.enc_shape, copy_bool = [False for k in range(len(self.enc_shape))]  ).cuda()
        # now one step in sequence
        shape = [1,1,1,64,64]

        self.decoder = LSTMmain(shape, self.enc_shape[-1], len(self.dec_shape), self.kernel_size, layer_output = 1, test_input = self.dec_shape, copy_bool = self.dec_copy_in,  second_debug = False).cuda()



        # initialise encoder and decoder network

    def input_test(self):
        """Checks and extracts information from the given structure argument

        Returns
        -------
        enc_shape: list of int
            shape argument specifying hidden layers of the encoder to be passed
            to LSTMmain constructor.
        dec_shape: list of int
            enc_shape: list of int
            shape argument specifying hidden layers of the decoder to be passed
            to LSTMmain constructor.
        enc_overlap: list of bool
            List of boolean values denoting whether each layer of the encoder
            overlaps with a decoder layer in the structure input and thus should
            copy out. To be passed to the LSTMmain 'copy_bool' argument
        dec_overlap: list of bool
            List of boolean values denoting whether each layer of the decoder
            overlaps with an encoder layer in the input and thus should
            copy in a hidden layer. To be passed to the LSTMmain 'copy_bool'
            argument.
        """
        copy_grid = []
        # finds dimensions of the encoder
        enc_layer = self.structure[0]
        enc_shape = enc_layer[enc_layer!=0]
        dec_layer = self.structure[1]
        dec_shape = dec_layer[dec_layer!=0]
#





        #set up boolean grid of where the overlaps are.
        for i in range(len(enc_layer)):
            if self.debug:
                print(enc_layer[i], dec_layer[i])
            if (enc_layer[i] != 0) and (dec_layer[i] != 0):
                copy_grid.append(True)
            else:
                copy_grid.append(False)


        enc_overlap = copy_grid[:len(enc_layer)-1]

        num_dec_zeros = len(dec_layer[dec_layer==0]) # will this break if no zeros?

        dec_overlap = copy_grid[num_dec_zeros:]

        return enc_shape, dec_shape, enc_overlap, dec_overlap

#         dec_overlap = copy_grid[]



#         [[1,2,3,0],
#          [0,2,3,1]]
    def forward(self, x):
        """Forward method of LSTMencdec

        Takes input image sequence produces a prediction of the next image in
        the sequence frame using a conditional LSTM encoder decoder structure

        Parameters
        ----------
        x: tensor of doubles
            Pytorch tensor of input image sequences. should be of size (minibatch
            size, sequence length, channels, height, width)

        Returns
        -------
        tensor:
            Tensor image prediction of size (minibatch size, sequence length,
            channels, height, width)
        """



        x, out_states = self.encoder(x, copy_in = False, copy_out = self.enc_copy_out)

#         print("length of out_states:", len(out_states))
#         print("contents out outstates are as follows:")
#         for i in out_states:
#             print("----------------------------------")
#             print("first object type:", type(i[0]))
# #             print("length of object:", len(i[0]))




        dummy_input = torch.zeros(x.shape)
        # technically a conditional loader - put x in there
        # puts in the last one as input - should make shorter.
        # presume coming out in the correct order - next try reversing to see if that helps
        x = x[:,-1:,:,:,:]
#         print("x shape encoder:", x.shape)
#         print(x.shape)


        res, _ = self.decoder(x, copy_in = out_states, copy_out = [False, False, False,False, False])
        print("FINISHING ONE PASS")
#         res = self.sig(res)
        return res

"""# dataset"""

class HDF5Dataset(Dataset):
    """dataset wrapper for hdf5 dataset to allow for lazy loading of data. This
    allows ram to be conserved.

    As the hdf5 dataset is not partitioned into test and validation, the dataset
    takes a shuffled list of indices to allow specification of training and
    validation sets.
    """

    def __init__(self, path, index_map, transform = None):
        """constructor for dataset

        Parameters
        ----------
        path: str
            Path to hdf5 dataset file to load
        index_map: list of ints
            List of shuffled indices. Allows shuffling of hdf5 dataset once extracted.
            The value at the list index is the mapped sample extracted from the
            hdf5 dataset. e.g A index list of [2,1,3] would mean that if the
            2nd value was called via __getitem__ by a dataloader, the 1st value
            in the dataframe would be returned. This provides less overhead than
            shuffling each selection
        """
#         %cd /content/drive/My \Drive/masters_project/data
        # changes directory to the one where needed.

        self.path = path

        self.index_map = index_map # maps to the index in the validation split
        # due to hdf5 lazy loading index map must be in ascending order.
        # this may be an issue as we should shuffle our dataset.
        # this will be raised as an issue as we consider a work around.
        # we should keep index map shuffled, and take the selection from the
        # shuffled map and select in ascending order.


        self.file = h5py.File(path, 'r')






    def __len__(self):
        return len(self.index_map)

    def __getitem__(self,i):

        i = self.index_map[i] # index maps from validation set to select new orders
#         print(i)
        if isinstance(i, list): # if i is a list.
            i.sort() # sorts into ascending order as specified above

        """TODO: CHECK IF THIS RETURNS DOUBLE"""

        predictor = torch.tensor(self.file["predictor"][i])

        truth = torch.tensor(self.file["truth"][i])

        return predictor, truth

def initialise_dataset_HDF5(valid_frac = 0.1, dataset_length = 9000):
    """
    Returns datasets for training and validation.

    Loads hdf5 custom dataset and utilising a shuffle split, dividing according
    to specified validation fraction.

    Parameters
    ----------
    valid_frac: float
        fraction of the loaded dataset to portion to validation
    dataset_length: int
        number of samples in the dataset to be loaded.

    Returns
    -------
    train_dataset: Pytorch dataset
        Dataset containing shuffled subset of samples for training
    validation_dataset: Pytorch dataset
        Dataset containing shuffled subset of samples for validation

    """

    if valid_frac != 0:

        dummy = np.array(range(dataset_length)) # clean this up - not really needed

        train_index, valid_index = validation_split(dummy, n_splits = 1, valid_fraction = 0.1, random_state = 0)

        train_dataset = HDF5Dataset("train_set.hdf5", index_map = train_index)

        valid_dataset = HDF5Dataset("test_set.hdf5", index_map = valid_index)

        return train_dataset, valid_dataset

    else:
        print("not a valid fraction for validation") # turn this into an assert.

def initialise_dataset_HDF5_full(dataset, valid_frac = 0.1, dataset_length = 9000, avg = 0, std = 0, application_boolean = [0,0,0,0,0]):
    """
    Returns datasets for training and validation.

    Loads hdf5 custom dataset and utilising a shuffle split, dividing according
    to specified validation fraction.

    Parameters
    ----------
    valid_frac: float
        fraction of the loaded dataset to portion to validation
    dataset_length: int
        number of samples in the dataset to be loaded.
    avg: list of floats
        Averages for each predictor channel in the input image sequences
    std: list of floats
        Standard deviation for each predictor channel in the input image sequence
    application_boolean: list of bools
        List of booleans specifying if which predictor channels should be standard
        score normalised

    Returns
    -------
    train_dataset: Pytorch dataset
        Dataset containing shuffled subset of samples for training
    validation_dataset: Pytorch dataset
        Dataset containing shuffled subset of samples for validation

    """

    if valid_frac != 0:

        dummy = np.array(range(dataset_length)) # clean this up - not really needed

        train_index, valid_index = validation_split(dummy, n_splits = 1, valid_fraction = 0.1, random_state = 0)

        train_dataset = HDF5Dataset_with_avgs(dataset,train_index, avg, std, application_boolean)

        valid_dataset = HDF5Dataset_with_avgs(dataset,valid_index, avg, std, application_boolean)


        return train_dataset, valid_dataset

    else:
        print("not a valid fraction for validation") # turn this into an assert.

"""# shuffling functions"""

def validation_split(data, n_splits = 1, valid_fraction = 0.1, random_state = 0):
    """Produces a stratified shuffle split of given dataset

    Wrapper around sklearn functions to produce stratified shuffle split of given
    dataset

    """
    dummy_array = np.zeros(len(data))
    split = StratifiedShuffleSplit(n_splits, test_size = valid_fraction, random_state = 0)
    generator = split.split(torch.tensor(dummy_array), torch.tensor(dummy_array))
    return [(a,b) for a, b in generator][0]

def unsqueeze_data(data):
    """
    Takes in moving MNIST object - must then account for
    """

    # split moving mnist data into predictor and ground truth.
    predictor = data[:][0].unsqueeze(2)
    predictor = predictor.double()

    truth = data[:][1].unsqueeze(2)# this should be the moving mnist sent in
    truth = truth.double()

    return predictor, truth
    # the data should now be unsqueezed.

#def initialise_dataset(data):
#    # unsqueeze data, adding a channel dimension for later convolution.
#    # this also gets rid of the annoying tuple format
#    predictor, truth = unsqueeze_data(data)
#
#    train_index, valid_index = validation_split(data)
#
#    train_predictor = predictor[train_index]
#    valid_predictor = predictor[valid_index]
#
#    train_truth = truth[train_index]
#    valid_truth = truth[valid_index]
#
#    train_dataset = SequenceDataset(train_predictor, train_truth)
#    valid_dataset = SequenceDataset(valid_predictor, valid_truth)
#
#    return train_dataset, valid_dataset

"""#TRAINING FUNCTIONS"""
# talk about this later.
def comb_loss_func(pred, y):
    """hopefully should work like kl and bce for VAE"""
    mse = nn.MSELoss()
    ssim = pytorch_ssim.SSIM()
    mse_loss = mse(pred, y[:,:1,:,:,:])
    ssim_loss = -ssim(pred[:,0,:,:,:], y[:,0,:,:,:])
    return mse_loss + ssim_loss

# %cd /content/drive/My\ Drive/masters_project/data/models
def train_enc_dec(model, optimizer, dataloader, loss_func = nn.MSELoss(), verbose = False):
    """Training function for encoder decoder models.

    Parameters
    ----------
    model: pytorch module
        Input model to be trained. Model should be end to end differentiable,
        and be inherited from nn.Module. model should be sent to the GPU prior
        to training, using model.cuda() or model.to(device)
    optimizer: pytorch optimizer.
        Pytorch optimizer to step model function. Adam / AMSGrad is recommended
    dataloader: pytorch dataloader
        Pytorch dataloader initialised with hdf5 averaged datasets
    loss_func: pytorch loss function
        Pytorch loss function
    verbose: bool
        Controls progress printing during training.

    Returns
    -------
    model: pytorch module
        returns the trained model after one epoch, i.e exposure to every piece
        of data in the dataset.
    tot_loss: float
        Average loss per sample for the training epoch
    """
    i = 0
    model.train() # enables training for model.
    tot_loss = 0
    for x, y in dataloader:
#         print("training")
        x = x.to(device) # send to cuda.
        y = y.to(device)
        optimizer.zero_grad() # zeros saved gradients in the optimizer.
        # prevents multiple stacking of gradients
        # this is important to do before we evaluate the model as the
        # model is currenly in model.train() mode

        prediction = model(x) #x should be properly formatted - of size
        """THIS DOESNT DEAL WITH SEQUENCE LENGTH VARIANCE OF PREDICTION OR Y"""

#         print("the size of prediction is:", prediction.shape)
        #last image sequence.

        """ACTUAL FUNCTION THATS BEEN COMMENTED OUT."""
#         loss = loss_func(prediction, y[:,:1,:,:,:])
        """CHANGED BECAUSE """
        if verbose:
            print(prediction.shape)
            print(y.shape)
        loss = loss_func(prediction[:,0,0], y)


#         loss = comb_loss_func(prediction, y)
#         print(prediction.shape)
#         print(y[:,:1,:,:,:].shape)
        """commented out """
#         loss = - loss_func(prediction[:,0,:,:,:], y[:,0,:,:,:])

# ssim_out = -ssim_loss(train[0][0][-1:],  x[0])
# ssim_value = - ssim_out.data



        loss.backward() # differentiates to find minimum.
#         printm()

        ##

    # implement the interpreteable stuff here.
        # as it is very unlikely we predict every pixel correctly we will not
        # use accuracy.
        # technically this is a regression problem, not a classification.


        optimizer.step() # steps forward the optimizer.
        # uses loss.backward() to give gradient.
        # loss is negative.
#         del x # make sure the garbage is collected.
#         del y
        """commented it out"""
        tot_loss += loss.item() # .data.item()
        if verbose:
            print("BATCH:")
            print(i)
        i += 1
#         if i == 20:
#             break
        if verbose:
            print("MSE_LOSS:", tot_loss / i)
        tot_loss /= i
    return model, tot_loss # trainloss, trainaccuracy

def validate(model, dataloader, loss_func = nn.MSELoss()):

    """as for train_enc_dec but without training - and acting upon validation
    data set
    """
    tot_loss = 0
    i = 0
    model.eval() # puts out of train mode so we do not mess up our gradients
    for x, y in dataloader:
        with torch.no_grad(): # no longer have to specify tensors
            # as volatile = True. as of modern pytorch use torch.no_grad.

            x=x.to(device) # send to cuda.
            y=y.to(device)
            prediction = model(x)

            loss = loss_func(prediction[:,0,0], y)

            tot_loss += loss.item()
            i += 1

            print("MSE_VALIDATION_LOSS:", tot_loss / i)



    return tot_loss / i # returns total loss averaged across the dataset.







def train_main(model, params, train, valid, epochs = 30, batch_size = 1):
    """Main training functions for the LSTMencdec

    Iterates over train_enc_dec to train the given model.

    Parameters
    ----------
    model: pytorch module
        returns the trained model after one epoch, i.e exposure to every piece
        of data in the dataset.
    train
    """
    # make sure model is ported to cuda
    # make sure seed has been specified if testing comparative approaches

#     if model.is_cuda == False:
#         model.to(device)

    # initialise optimizer on model parameters
    # chann
    optimizer = torch.optim.Adam(model.parameters(), lr = 0.005, amsgrad= True)
    loss_func = nn.MSELoss()
#     loss_func = nn.BCELoss()
#     loss_func = pytorch_ssim.SSIM()

    train_loader = DataLoader(train, batch_size = batch_size, shuffle = True) # implement moving MNIST data input
    validation_loader = DataLoader(valid, batch_size = batch_size, shuffle = False) # implement moving MNIST

    for epoch in range(epochs):

        train_enc_dec(model, optimizer, train_loader, loss_func = loss_func) # changed


        torch.save(optimizer.state_dict(), F"Adam_new_ams_changed"+str(epoch)+".pth")
        torch.save(model.state_dict(), F"Test_new_ams_changed"+str(epoch)+".pth")


#         validate(model, validation_loader)

    return model, optimizer

"""# hdf5 with avgs"""

class HDF5Dataset_with_avgs(Dataset):
    """dataset wrapper for hdf5 dataset to allow for lazy loading of data. This
    allows ram to be conserved.

    As the hdf5 dataset is not partitioned into test and validation sets, the dataset
    takes a shuffled list of indices to allow specification of training and
    validation sets. The dataet lazy loads from hdf5 datasets and applies standard
    score normalisation in the __getitem__ method.

    Parameters
    ----------
    path: str
        filepath to hdf5 dataset to be loaded.
    index_map: list of ints
        List of shuffled indices. Allows shuffling of hdf5 dataset once extracted.
        The value at the list index is the mapped sample extracted from the
        hdf5 dataset. e.g A index list of [2,1,3] would mean that if the
        2nd value was called via __getitem__ by a dataloader, the 1st value
        in the dataframe would be returned. This provides less overhead than
        shuffling each selection.
    avg: list of floats
        List of averages for every channel in image sequence loaded. Length should
        equal number of channels in dataset image sequence
    std: list of floats
        List of standard deviations for every channel in image sequence loaded.
        Length should equal number of channels in dataset image sequence.
    application_boolean: list of bools
        List of bools indicating whether standard score normalisation is to be
        applied to each layer. Length should equal number of channels in dataset
        image sequence.
    """

    def __init__(self, path, index_map, avg, std, application_boolean, transform = None):
        """Constructor for hdf5 dataset
        """
#         %cd /content/drive/My \Drive/masters_project/data
        # changes directory to the one where needed.

        self.path = path

        self.index_map = list(index_map) # maps to the index in the validation split
        # due to hdf5 lazy loading index map must be in ascending order.
        # this may be an issue as we should shuffle our dataset.
        # this will be raised as an issue as we consider a work around.
        # we should keep index map shuffled, and take the selection from the
        # shuffled map and select in ascending order.
        self.avg = avg
        self.std = std
        self.application_boolean = application_boolean

        self.file = h5py.File(path, 'r')

#         for i in range(len(application_boolean)):
#             # i.e gaussian transformation doesnt happen. (x - mu / sigma)
#             if application_boolean == 0:
#                 self.avg[i] = 0
#                 self.std[i] = 1










    def __len__(self):
        return len(self.index_map)

    def __getitem__(self,i):

        i = self.index_map[i] # index maps from validation set to select new orders
#         print(i)
        if isinstance(i, list): # if i is a list.
            i.sort() # sorts into ascending order as specified above

        """TODO: CHECK IF THIS RETURNS DOUBLE"""

        predictor = torch.tensor(self.file["predictor"][i])
#         print("predictor shape:", predictor.shape)
        # is of batch size, seq length,


        truth = torch.tensor(self.file["truth"][i])
#         print("truth shape:", truth.shape)
        # only on layer so not in loop.

#        truth -= self.avg[0]
#        truth /= self.std[0]

        if isinstance(i, list):
            for j in range(len(self.avg)):
                if self.application_boolean[j]:
                    predictor[:,:,j] -= self.avg[j]
                    predictor[:,:,j] /= self.std[j]


        else:
            for j in range(len(self.avg)):
                if self.application_boolean[j]:
                    predictor[:,j] -= self.avg[j]
                    predictor[:,j] /= self.std[j]


#             #i.e if we are returning a single index.
# #         # the value of truth should be [0] in the predictor array.
#         for j in range(len(self.avg)):
#             if self.application_boolean[j]:
#                 predictor[:,:,j] -= self.avg[j]
#                 predictor[:,:,j] /= self.std[j]

#                 # sort out dimensions of truth at some point





        return predictor, truth

"""# wrapper"""

def wrapper_full(name, optimizer,  structure, loss_func, avg, std, application_boolean, lr = None, epochs = 50, kernel_size = 3, batch_size = 50):
    """Training wrapper for LSTM encoder decoder models.

    Trains supplied model using train_enc_dec fucntions. Logs model hyperparameters
    and trainging and validation losses in csv training log. Saves the model and
    optimiser state dictionaries after each epoch in order to allow for easy
    checkpointing.

    Parameters
    ----------
    name: str
        filename to save CSV training logs as.
    optimizer: pytorch optimizer
        The desired optimizer needed to train the model
    structure: array of ints
        Structure argument to be passed to lstmencdec. See LSTMencdec for explanation
        of structure format.
    loss_func: pytorch module
        Loss function to be used to calculate training and validation losses.
        The loss should be a CLASS instance of the pytorch loss function, not
        a functinal implementation.
    avg: list of floats
        List of averages for every channel in image sequence loaded. Length should
        equal number of channels in dataset image sequence
    std: list of floats
        List of standard deviations for every channel in image sequence loaded.
        Length should equal number of channels in dataset image sequence.
    application_boolean: list of bools
        List of bools indicating whether standard score normalisation is to be
        applied to each layer. Length should equal number of channels in dataset
        image sequence.
    lr: float
        Learning rate for the optimizer
    epochs: int
        Number of epochs to train the model for
    kernel_size: int
        Size of convolution kernel for the LSTMencoderdecoder
    batch_size: int
        Number of samples in each training minibatch.

    Returns
    -------
    bool:
        indicates if training has been completed.
    """
    f = open(name + ".csv", 'w') # open csv file for saving

    if torch.cuda.device_count() > 1:
        model = nn.DataParallel(LSTMencdec_onestep(structure, 5, kernel_size = kernel_size)).to(device)
    else:
        model = LSTMencdec_onestep(structure, 5, kernel_size = kernel_size).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr = lr, amsgrad= True)

    # put in structure.
    f.write("Structure: \n")

    for i in range(len(structure)):
        for j in range(len(structure[0])):
            f.write("{},".format(structure[i,j]))
        f.write("\n") # new line

    f.write("Parameters:\n")
    f.write("optimizer, epochs, learning rate, kernel size \n")

    if lr != None:
        # optimizer problems

        f.write("{},{},{},{},{}\n".format("test", epochs, lr, kernel_size, batch_size))
    else:
        f.write("{},{},{},{},{}\n".format("othertest", epochs, "Default", kernel_size, batch_size))

    f.write("loss_func:\n")
    f.write(loss_func.__repr__() + "\n")

    f.write("optimizer:\n")
    f.write(optimizer.__repr__() + "\n")

    f.write("\n\n\n")
    f.write("TRAINING\n")

    # now we define the training functions
#     train, valid = initialise_dataset_HDF5()

#     index_map = np.arange(0, 93620,1)# dummy index_map just to make sure trains correctly.
#     train = HDF5Dataset_with_avgs('data_prio_run_test5.hdf5', list(index_map),avg, std, apbln)
    """CHANGED THE ABOVE TO LIST - BETTER INDEXING?"""
    # put model together with different size
    # model test - put it together.
    # now we train the model

    train, valid = initialise_dataset_HDF5_full('train_fixed_25.hdf5', valid_frac = 0.1, dataset_length = 56413,avg = avg, std = std, application_boolean=application_boolean)



    # ignore this one.

#     model, optimizer = train_main(test_model, 1, train, valid, epochs = epochs, batch_size = 50)

    loss_func = loss_func

#     optimizer = torch.optim.Adam(model.parameters(), lr = lr, amsgrad= True)

#     loss_func = nn.BCELoss()
#     loss_func = pytorch_ssim.SSIM()
    f.close()

    train_loader = DataLoader(train, batch_size = batch_size, shuffle = True) # implement moving MNIST data input
    valid_loader = DataLoader(valid, batch_size = 2000, shuffle = False) # implement moving MNIST

    for epoch in range(epochs):

        # does is matter that we arent returning the model?
        _, loss = train_enc_dec(model, optimizer, train_loader, loss_func = loss_func) # changed

        torch.save(optimizer.state_dict(), name+str(epoch)+"optimizer.pth")
        torch.save(model.state_dict(), name+str(epoch)+".pth")

        valid_loss = validate(model, valid_loader, loss_func = loss_func) # validation - need to shuffle split.

        f = open(name + ".csv", 'a') # open csv file for saving

        f.write(str(loss) + "," + str(valid_loss) + "\n")

        f.close()

#         torch.save(optimizer.state_dict(), name+str(epoch)+".pth")
#         torch.save(model.state_dict(), name+str(epoch)+".pth")
    return True

#     f.close()


#structure = np.array([[12,24,0,0,0],[0,24,12,6,5]])
#
#test_model = LSTMencdec_onestep(structure, 1, kernel_size = 3).to(device)


def test_image_save(model, train_loader, name, sample = 7):
    """Saves comparison between prediction of the given model and ground truth.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset from which input sequence to be visualised is stored
    name: str
        Filename to save visualised comparison in.
    sample: int
        Sample of the input dataset to be predicted.
    """
    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())

    x = x.cpu()






    fig, axes = plt.subplots(1,2)
    print(x.shape)
    print(b.shape)
    axes[0].imshow(x[sample][0][0])
    axes[1].imshow(b[sample])

    axes[1].set_title("truth")
    axes[0].set_title("Prediction")
    fig.suptitle("Prediction of:" + name)
    fig.savefig(name + "comparison.pdf")
#     print(b[7])
#     print(x[7][0][0])
    fig, axes = plt.subplots(10,1,figsize=(32,32))
    for i in range(10):
        axes[i].imshow(a[sample][i][0])



""" FROM MODEL_TESTING_HPC"""


def f1(model, train_loader, avg = 'macro'):
    """Produces average F1 score for each image prediction in the dataset.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset from which input sequence to be visualised is stored
    avg: str
        method of averaging over each multilabel image. see sklearn.metrics.f1_score
        for specification of the average key types


    """
    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())


    x = x.cpu()
    x[x>0] = 1
    x[0>x] = 0
#     print(x[0][0][0])
    print(x[222,0,0].shape)
    print(b[222].shape)
#     print(b)
    print(b[222].view(-1, 256).numpy().shape)
    truth = set(list(b[222].view(256).numpy()))
    pred = set(list(x[222,0,0].view(256).numpy()))
    print(truth - pred)
    scores = []
    for i in range(len(b)):
        score = f1_score(b[i].view(256).numpy(), x[i,0,0].view(256).numpy(), average=avg)
        scores.append(score)
        truth = set(list(b[i].view(256).numpy()))
        pred = set(list(x[i,0,0].view(256).numpy()))
        if len(truth - pred) > 0:
            print(i)
#     score = f1_score(b[222].numpy(), b[222].numpy(), average=avg)
    return scores
#     print(score)





#     print(x[sample][0][0])

def metrics(model, train_loader, name = 'default', verbose = True, save = True):
    """Calculate TN, FN, TP, FP, precision, recall and f1 score.

    Calculates the true negative, false negative, true positive, false positive,
    precison, recall, and multilabel f_1 score for the model predictions of a
    supplied data sample. The F1 score is calculated according to XXXX. To offset
    bias in multilabel sampling. Produces CSV storing performance metrics for
    later analysis.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset in which input sequence to be visualised is stored.
    name: str
        filename to store metrics CSV under.
    verbose: bool
        Controls print output of metrics
    save: bool
        controls whether metrics will be saved in csv

    Returns
    -------
    list:
        true negative, false negative, true positive, false positive,
        precison, recall, and multilabel f_1 score for the model predictions.
    """
    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())


    x = x.cpu()
    x[x>0] = 1
    x[0>x] = 0

    # reshape
    truth = b.view(-1,256).numpy()
    pred = x[:,0,0].view(-1,256).numpy()
    tn = 0
    tp = 0
    fn = 0
    fp = 0

    print(truth.shape)
    print(pred.shape)
    for i in range(len(b)):
        for j in range(256):
            # true positive
            if (truth[i][j] == 1) and (pred[i][j] == 1):
                tp += 1
            # true negative
            if (truth[i][j] == 0) and (pred[i][j] == 0):
                tn += 1

            #false positive
            if (truth[i][j] == 0) and (pred[i][j] == 1):
                fp +=1
            #false negative
            if (truth[i][j] == 1) and (pred[i][j] == 0):
                fn += 1

    prec = tp / (tp + fp)
    rec = tp/ (tp + fn)

    f_1 = 2 * prec * rec / (prec + rec)

    if verbose:
        print("tn:" ,tn)
        print("tp:" , tp)
        print("fn:" , fn)
        print("fp" ,fp)
        print("prec:" ,prec)
        print("rec:" , rec)
        print("f1: ", f_1)

    if save:
        f = open(name + "metrics.csv", 'w')
        for i in [tn, tp, fn, fp, prec, rec, f_1]:

            f.write(str(i) + "\n")

        f.close()
    return [tn, fn, tp, fp, prec, rec, f_1]

def area_under_curve_metrics(model, train_loader, name = 'default', verbose = True, save = True):
    """Calculates the Area Under the Reciever Operator Charactersitc (AUROC)
    curve and the Area Under the Precision Recall (AUPR) curve. Uses
    average_precision_score to calculate AUPR.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset in which input sequence to be visualised is stored.
    name: str
        filename to store metrics CSV under.
    verbose: bool
        Controls print output of metrics
    save: bool
        controls whether metrics will be saved in csv

    Returns
    -------
    list:
        list of [AUROC, AUPR]


    """
    sig = nn.Sigmoid()
    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())

    x = x.cpu()
    truth = b.view(-1,256).numpy()
    pred = sig(x[:,0,0].view(-1,256)).numpy()
#     truth = b.contiguous().view(-1).numpy()
#     pred = sig(x[:,0,0].contiguous().view(-1)).numpy()
#     fpr, tpr, thresholds = roc_curve(truth, pred)
#     plt.plot(fpr, tpr)
#     plt.plot(fpr, fpr)
    r = roc_auc_score(truth, pred)
    av = average_precision_score(truth, pred)
    if verbose:
        print(r)
        print(av)

    if save:
        f = open(name + "metrics.csv", 'a')
        for i in [r,av]:

            f.write(str(i) + "\n")

        f.close()
    return [r, av]

def brier_score(model, train_loader, name = 'default', verbose = True, save = True):
    """Calculates the average brier score for each prediction. Saves prediction
    in metrics csv.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset in which input sequence to be visualised is stored.
    name: str
        filename to store metrics CSV under.
    verbose: bool
        Controls print output of metrics
    save: bool
        controls whether metrics will be saved in csv

    Returns
    -------
    float:
        brier score.

    """
    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())


    x = x.cpu()
    x[x>0] = 1
    x[0>x] = 0

    diff = (x[:,0,0] - b)**2
    brier = np.average(diff)

    if verbose:
        print(brier)

    if save:
        f = open(name + "metrics.csv", 'a')
        f.write(str(brier) + "\n")
        f.close()
    return brier

def full_metrics(model, train_loader, name = 'default'):
    """extracts all performance metrics from one data sample.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset in which input sequence to be visualised is stored.
    name: str
        filename to store metrics CSV under.
    """
    metrics(model, train_loader, name = name)
    area_under_curve_metrics(model, train_loader, name = name)
    brier_score(model, train_loader, name = name)

def curves(model, train_loader):
    """PLots ROC curves for diagonal pixels in image prediction

    Plots ROC curves for diagonal pixels in the image predictions.This is done
    to reduce overcrowding of plots.

    Parameters
    ----------
    model:
        Trained model to visualise prediction of.
    train_loader:
        Dataloader of dataset in which input sequence to be visualised is stored.


    """
#     dataframe = pd.dataframe()
    sig = nn.Sigmoid()
    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())

    x = x.cpu()
    truth = b.view(-1,256).numpy()
    pred = sig(x[:,0,0].view(-1,256)).numpy()
    plt.figure()
#     for i in range(16):
    for j in range(16):
        t = b[:,j,j].contiguous().view(-1).numpy()
        p = sig(x[:,0,0,j,j].contiguous().view(-1)).numpy()
        fpr, tpr, thresholds = roc_curve(t, p)
        plt.plot(fpr, tpr)
    plt.plot(fpr, fpr)
    plt.xlim(0, 1.1)
    plt.ylim(0,1.1)

    plt.show()

def batch_loss_histogram(model, train_loader, loss_func):

    model.eval()
    # calculate x and prediction
    for a, b in train_loader:
        # a in input, b is truth
        break # train loader cannot be indexed


    with torch.no_grad():
        x = model(a.cuda())


        x = x.cpu()
#     print(x.shape)
    # now over each one in x - we do
        #loss_func = nn.BCEWithLogitsLoss()
        loss = []
        for i in range(len(x)):
            loss.append(loss_func(x[i,:,0],b[i:i+1]).item())





    return loss
#
#d = np.load("weights_bce.npy")
#weights = torch.tensor(d)
#weights = weights // 2
#weights = weights.to(device)
#b = nn.BCEWithLogitsLoss(pos_weight=weights)
#
#
#
#avg = np.load("fixed_25_avg.npy")
#std = np.load("fixed_25_std.npy")
## changed below
#apbln = [0,1,0,0,1] # think this is correct
#
#wrapper_full("valid_test", 10, structure, b, avg, std, apbln, lr = 0.001, epochs = 2000, batch_size = 200)


